version: '3.9'

services:
  web:
    build:
      context: .
      args:
        SKIP_APP_BUILD: "1"
    command: sh -lc "\
      corepack enable && corepack prepare pnpm@9.12.3 --activate && \
      pnpm install && \
      pnpm prisma generate && \
      pnpm prisma migrate deploy || true && \
      pnpm dev --host 0.0.0.0 --port 5173"
    volumes:
      - ./:/app
      - web_node_modules:/app/node_modules
    env_file:
      - .env
    ports:
      - "5173:5173"

volumes:
  web_node_modules:


